shellhacksapp/urls.py
from django.urls import path, include
from . import views as v

app_name = 'shellhacksapp'

urlpatterns = [
    path('', v.hello, name = 'home'),
    path('fetch_financial_data/', v.get_financial_data, name = 'fetch_financial_data'),
    path('google_data/', v.google_data, name='google_data'),
    path('get_company_data/', v.get_company_data, name='get_company_data'),
    path('comparison/', v.comparison_step_one, name='comparison'),
    path('comparison_two/', v.comparison_step_two, name = 'comparison_two'),
    path('comparison_result/', v.comparison_result, name = 'comparison_result'),
    path('comparison_step_two/', v.comparison_step_two, name='comparison_step_two'),

]

shellhacksproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shellhacksapp.urls')),
    # path('finance/', include('get_finance_data.urls')),
]

shellhacksapp/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

class Company(models.Model):
    name = models.CharField(max_length=255)
    stock_price = models.DecimalField(max_digits=10, decimal_places=2)
    high_52week = models.DecimalField(max_digits=10, decimal_places=2)
    low_52week = models.DecimalField(max_digits=10, decimal_places=2)
    profit_margin = models.DecimalField(max_digits=5, decimal_places=2)
    volume = models.IntegerField()
    pe_ratio = models.DecimalField(max_digits=5, decimal_places=2)

    def str(self):
        return self.name

shellhacksapp/forms.py
from django import forms
from .models import Company
from django.forms import ModelForm
from .models import *


class CompanySearchForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['name']  

shellhacksapp/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse 
import yfinance as yf
from .models import Product
from .models import *
from .dict import companies_500
from django.shortcuts import render, reverse
from .models import Company 


def hello(request):
    return render(request, 'main.html')





def get_financial_data(request):
    companies_data = {
        "GOOGL": "Google",
        "AAPL": "Apple",
        "MSFT": "Microsoft"
    }

    data_fields = ["regularMarketPrice", "fiftyTwoWeekHigh", "fiftyTwoWeekLow", "profitMargins", "averageVolume", "regularMarketVolume", "trailingPE"]

    company_data = {}

    for symbol, name in companies_data.items():
        try:
            stock = yf.Ticker(symbol)
            data = stock.info
            company_data[name] = {field: data.get(field) for field in data_fields}
        except Exception as e:
            print(f"Error fetching data for {name} ({symbol}): {str(e)}")

    for name, data in company_data.items():
        print(f"Data for {name}:")
        
       

        print(f"52-Week High:           ${data['fiftyTwoWeekHigh']:.2f}")
        print(f"52-Week Low:            ${data['fiftyTwoWeekLow']:.2f}")
        print(f"Profit Margin:           {data['profitMargins']:.2%}")
        print(f"Average Volume:          {data['averageVolume']:,} shares")
        print(f"Volume:                  {data['regularMarketVolume']:,} shares")
        print(f"Price-to-Earnings Ratio: {data['trailingPE']:.2f}")
        print("\n")
    context = {'company_data': company_data}

   
    return render(request, 'company_data_template.html', context)




def google_data(request):
   
    ticker_symbol = "GOOG"

    # Fetch Google's stock data
    goog = yf.Ticker(ticker_symbol)

    # Get the user's input from the query parameter 'search_query'
    user_input = request.GET.get('search_query')

  
    stock_info = {
        "company_name": goog.info["longName"],  
        "total_price": goog.history(period="1d")["Close"].iloc[0],
        "week_high": goog.history(period="1y")["High"].max(),
        "week_low": goog.history(period="1y")["Low"].min(),
        "profit_margin": goog.info["profitMargins"] * 100,
        "average_volume": goog.history(period="1y")["Volume"].mean(),
        "pe_ratio": goog.info["trailingPE"]
    }

   
    context = {
        "stock_info": stock_info,
        "user_input": user_input, 
    }


    return render(request, 'google_data_template.html', context)

def comparison(request):
    return render(request, 'comparison.html')



from django.shortcuts import render, redirect
from .models import Company  

def get_company_data(request):
    if request.method == 'POST':
        company_name = request.POST.get('company_name_firstone')

      
        company = Company.objects.filter(name__iexact=company_name).first()

        if company:
          
            request.session['company_name_firstone'] = company_name
        else:
            print("Company not found")
   

      
        company_tickers = companies_500

        # Check if the selected company name exists in the dictionary
        if company_name in company_tickers:
            ticker_symbol = company_tickers[company_name]
        else:
            print("Company not in S&P 500 ")
            return render(request, 'error_template.html', {"error_message": "Company not in S&P 500"})

        try:
            # Fetch the stock data for the selected company
            company_stock = yf.Ticker(ticker_symbol)

            # Get the relevant stock information
            stock_info = {
                'company_name': company_name,
                "total_price": company_stock.history(period="1d")["Close"].iloc[0],
                "week_high": company_stock.history(period="1y")["High"].max(),
                "week_low": company_stock.history(period="1y")["Low"].min(),
                "profit_margin": company_stock.info["profitMargins"] * 100,
                "average_volume": company_stock.history(period="1y")["Volume"].mean(),
                "pe_ratio": company_stock.info["trailingPE"]
            }

            # Create a context dictionary to pass the data to the template
            context = {"stock_info": stock_info, "selected_company": company_name}

            # Render the template with the data
            return render(request, 'google_data_template.html', context)
        except Exception as e:
            error_message = f"Error fetching data for {company_name}: {str(e)}"
            print(error_message)

  
    return render(request, 'main.html')




def comparison_step_one(request):
    if request.method == 'POST':
        company_name = request.POST.get('company_name')
        company = Company.objects.filter(name__iexact=company_name).first()

        if company:
         
            request.session['company_name_1'] = company_name
            return redirect('comparison_step_two')
        else:
            print("Company not found")
       
        
     
        return redirect(reverse('shellhacksapp:comparison_two'))

    return render(request, 'comparison.html')

def comparison_step_two(request):
    if request.method == 'POST':
        company_name = request.POST.get('company_name')
        
        request.session['company_name_2'] = company_name
        return redirect('shellhacksapp:comparison_result')

    return render(request, 'comparison_two.html')


def comparison_result(request):
    company_name_1 = request.session.get('company_name_1')
    company_name_2 = request.session.get('company_name_2')

    # Check if both company names are available in the session
    if company_name_1 and company_name_2:
        
        company_tickers = companies_500
        ticker_symbol_1 = company_tickers.get(company_name_1)
        ticker_symbol_2 = company_tickers.get(company_name_2)

        if ticker_symbol_1 and ticker_symbol_2:
            try:
              
                company_stock_1 = yf.Ticker(ticker_symbol_1)
                company_stock_2 = yf.Ticker(ticker_symbol_2)

               
                stock_info_1 = {
                    'company_name': company_name_1,
                    "total_price": company_stock_1.history(period="1d")["Close"].iloc[0],
                    "week_high": company_stock_1.history(period="1y")["High"].max(),
                    "week_low": company_stock_1.history(period="1y")["Low"].min(),
                    "profit_margin": company_stock_1.info["profitMargins"] * 100,
                    "average_volume": company_stock_1.history(period="1y")["Volume"].mean(),
                    "pe_ratio": company_stock_1.info["trailingPE"]
                }

                stock_info_2 = {
                    'company_name': company_name_2,
                    "total_price": company_stock_2.history(period="1d")["Close"].iloc[0],
                    "week_high": company_stock_2.history(period="1y")["High"].max(),
                    "week_low": company_stock_2.history(period="1y")["Low"].min(),
                    "profit_margin": company_stock_2.info["profitMargins"] * 100,
                    "average_volume": company_stock_2.history(period="1y")["Volume"].mean(),
                    "pe_ratio": company_stock_2.info["trailingPE"]
                }

                
                context = {
                    "stock_info_1": stock_info_1,
                    "stock_info_2": stock_info_2,
                }

               
                return render(request, 'comparison_result.html', context)
            except Exception as e:
                error_message = f"Error fetching data: {str(e)}"
                print(error_message)

   
    return render(request, 'comparison_result.html')

shellhacksapp/templates/company_data_template.html
{% load static %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


<!DOCTYPE html>
<html>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <div class="container-fluid">
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/comparison/">Comparison Chart</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" >Companies</a>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="#">Login</a>
                </li>
              </ul>
              
      </nav>
<head>
    <title>Company Data</title>
</head>
<body>
    <form class="d-flex" style = "margin-left: 125px; width: 500px; margin-top: 30px;">
        <input class="form-control me-2" type="search" placeholder="Search Company" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

    <style>
        
        .centered-list {
            width: 80%; 
            margin: 0 auto; 
            margin-top: 20px;
        }
        
        .list-group-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }          
    </style>


      
    {% for name, data in company_data.items %}
    <ul class="list-group centered-list">
        <li class="list-group-item active">{{ name }}</li>
        <li class="list-group-item"><span>52-Week High:</span> <span>${{ data.fiftyTwoWeekHigh|floatformat:2 }}</span></li>
        <li class="list-group-item"><span>52-Week Low:</span> <span>${{ data.fiftyTwoWeekLow|floatformat:2 }}</span></li>
        <li class="list-group-item"><span>Profit Margin:</span> <span>{{ data.profitMargins|floatformat:2 }}%</span></li>
        <li class="list-group-item"><span>Average Volume:</span> <span>{{ data.averageVolume|floatformat:2 }} shares</span></li>
        <li class="list-group-item"><span>Volume:</span> <span>{{ data.regularMarketVolume|floatformat:2 }} shares</span></li>
        <li class="list-group-item"><span>Price-to-Earnings Ratio:</span> <span>{{ data.trailingPE|floatformat:2 }}</span></li>
    </ul>
    
    
    {% endfor %}

shellhacksapp/templates/comparison.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Company Comparing</title>
</head>
<body>


</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <div class="container-fluid">
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/google_data/">Companies</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/comparison/">Comparison Chart</a>
                  </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="#">Login</a>
                </li>
              </ul>
              
      </nav>
     
    
    <form method="POST" action="{% url 'shellhacksapp:comparison' %}" class="d-flex" style="margin-left: 255px;margin-right: auto; width: 500px; margin-top: 70px;">
        {% csrf_token %}
        <input name="company_name" class="form-control me-2" type="search" placeholder="Search Company" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    

    <style>
        .container {
            width: 800px; 
            margin: 0 auto; 
            
        }
        .centered-list {
            width: 80%; 
            margin: 0 auto; 
            margin-top: 20px;
        }
    
        .list-group {
            width: 100%; 
        }
        .list-item-label {
            display: inline-block; /* Make the label and value inline-block elements */
            width: 150px; /* Adjust the width as needed */
            text-align: right; /* Align the label text to the right */
            margin-right: 10px; /* Add some right margin for spacing */
        }
        .list-group-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

shellhacksapp/templates/comparison_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Company Comparison</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/google_data/">Companies</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/comparison/">Comparison Chart</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Login</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <ul class="list-group">
                    <li class="list-group-item active" style="background-color: #e3f2fd; color: black;"><span>{{ stock_info_1.company_name }}</span></li>
                    <li class="list-group-item">Total Price: ${{ stock_info_1.total_price|floatformat:"2" }}</li>
                    <li class="list-group-item">52-Week High: ${{ stock_info_1.week_high|floatformat:"2" }}</li>
                    <li class="list-group-item">52-Week Low: ${{ stock_info_1.week_low|floatformat:"2" }}</li>
                    <li class="list-group-item">Profit Margin: {{ stock_info_1.profit_margin|floatformat:"2" }}%</li>
                    <li class="list-group-item">Average Volume: {{ stock_info_1.average_volume|floatformat:"2" }} shares</li>
                    <li class="list-group-item">Price to Earnings Ratio: {{ stock_info_1.pe_ratio|floatformat:"2" }}</li>
                </ul>
            </div>
            <div class="col-md-6">
                <ul class="list-group">
                    <li class="list-group-item active" style="background-color: #e3f2fd; color: black;"><span>{{ stock_info_2.company_name }}</span></li>
                    <li class="list-group-item">Total Price: ${{ stock_info_2.total_price|floatformat:"2" }}</li>
                    <li class="list-group-item">52-Week High: ${{ stock_info_2.week_high|floatformat:"2" }}</li>
                    <li class="list-group-item">52-Week Low: ${{ stock_info_2.week_low|floatformat:"2" }}</li>
                    <li class="list-group-item">Profit Margin: {{ stock_info_2.profit_margin|floatformat:"2" }}%</li>
                    <li class="list-group-item">Average Volume: {{ stock_info_2.average_volume|floatformat:"2" }} shares</li>
                    <li class="list-group-item">Price to Earnings Ratio: {{ stock_info_2.pe_ratio|floatformat:"2" }}</li>
                </ul>
            </div>
        </div>
    </div>


</body>
</html>

shellhacksapp/templates/comparison_two.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Company Compaing</title>
</head>
<body>


</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <div class="container-fluid">
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/google_data/">Companies</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/comparison/">Comparison Chart</a>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="#">Login</a>
                </li>
              </ul>
              
      </nav>

      <form method="POST" action="{% url 'shellhacksapp:comparison_step_two' %}" class="d-flex" style="margin-left: 255px;margin-right: auto; width: 500px; margin-top: 70px;">
        {% csrf_token %}
        <input name="company_name" class="form-control me-2" type="search" placeholder="Search your second company" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    <style>
        .container {
            width: 800px; 
            margin: 0 auto; 
            
        }
        .centered-list {
            width: 80%; 
            margin: 0 auto; 
            margin-top: 20px;
        }
    
        .list-group {
            width: 100%; 
        }
        .list-item-label {
            display: inline-block; /* Make the label and value inline-block elements */
            width: 150px; /* Adjust the width as needed */
            text-align: right; /* Align the label text to the right */
            margin-right: 10px; /* Add some right margin for spacing */
        }
        .list-group-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

    </style>

    

shellhacksapp/templates/error_template.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<div class="alert alert-danger" role="alert">
    This company is not in S&P 500!
  </div>
<nav class="navbar navbar-expand-lg navbar-light" >
    <div class="container-fluid">
      
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Return home</a>
          </li>
        </ul>
         
        
          
  </nav>

shellhacksapp/templates/google_data_template.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Company Stock Data</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <div class="container-fluid">
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/google_data/">Companies</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/comparison/">Comparison Chart</a>
                  </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="#">Login</a>
                </li>
              </ul>
              
      </nav>


    <form method="POST" action="{% url 'shellhacksapp:get_company_data' %}" class="d-flex" style="margin-left: 255px;margin-right: auto; width: 500px; margin-top: 70px;">
        {% csrf_token %}
        <input name="company_name" class="form-control me-2" type="search" placeholder="Search Company" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    <style>
        .container {
            width: 800px; 
            margin: 0 auto; 
            
        }
        .centered-list {
            width: 80%; 
            margin: 0 auto; 
            margin-top: 20px;
        }
    
        .list-group {
            width: 100%; 
        }
        .list-item-label {
            display: inline-block;
            width: 150px; 
            text-align: right; 
            margin-right: 10px; 
        }
        .list-group-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        
           
        
    </style>
    
    <div class="container">
        <ul class="list-group">
            <li class="list-group-item active" style="background-color: #e3f2fd; color: black;"><span>{{ stock_info.company_name }}</span></li>
            <li class="list-group-item"><span>Total Price:</span> <span>${{ stock_info.total_price|floatformat:"2" }}</span></li>
            <li class="list-group-item"><span>52-Week High:</span> <span>${{ stock_info.week_high|floatformat:"2" }}</span></li>
            <li class="list-group-item"><span>52-Week Low:</span> <span>${{ stock_info.week_low|floatformat:"2" }}</span></li>
            <li class="list-group-item"><span>Profit Margin:</span> <span>{{ stock_info.profit_margin|floatformat:"2" }}%</span></li>
            <li class="list-group-item"><span>Average Volume:</span> <span>{{ stock_info.average_volume|floatformat:"2" }} shares</span></li>
            <li class="list-group-item"><span>Price to Earnings Ratio:</span> <span>{{ stock_info.pe_ratio|floatformat:"2" }}</span></li>
        </ul>
    </div>
    


</body>
</html>

shellhacksapp/templates/main.html
{% load static %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="main.css">




  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">
      
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/google_data/">Companies</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/comparison/">Comparison Chart</a>
              </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="#">Login</a>
            </li>
          </ul>
          
  </nav>


<div class="card" style="width: 900px; margin-right: auto; margin-left: auto; margin-top: 30px;">
    <img src="{% static 'img/building.jpeg' %}" class="card-img-top" style="height: 400px;">
    <div class="card-body">
      <h5 class="card-title">S&P 500</h5>
      <p class="card-text">S&P is an index fund that has 500 companies consisting of 503 stocks. Explore the market summary of each companys' stock and compare them with each other!</p>
      <a href="google_data" class="btn btn-primary">Get started</a>
    </div>
  </div>